config {
    type: "view",
    name: "source",
    assertions: {
        uniqueKeys: [
            ["fruit"]
        ],
        rowConditions: [
            "number > 0"
        ]
    }
}

SELECT
  "apples" AS fruit,
  3 AS number
UNION ALL
SELECT
  "oranges" AS fruit,
  5 AS number
UNION ALL
SELECT
  "pears" AS fruit,
  1 AS number
UNION ALL
SELECT
  "bananas" AS fruit,
  0 AS number
